---
name: couchdb-service-broker
director_uuid: 73046174-ab9b-45e2-a4b5-d1c1695d4f65
releases:
- name: couchdb-service-broker
  version: latest
update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 3
stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3468.5

############################################################
instance_groups:
- name: couchdb3
  instances: 3
#  azs: [z1]
  jobs:
  - name: couchdb2
    release: couchdb-service-broker
#  - name: node-exporter
#  - name: mongodb-exporter
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default

#- name: replset
#  instances: 1
#  lifecycle: errand
#  jobs:
#  - name: replset
#    release: mongodb3
#  vm_type: default
#  stemcell: default
#  persistent_disk_type: default
#  networks:
#  - name: default


